version: '3.5'
services:
  ru-smart-caching:   
    image: redis:6.0
    container_name: ru-smart-caching
    restart: always    
    ports:
      - xxxxxxxx:6379
    volumes:
      - ./redis_data:/data
      - ./redis_config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass xxxxxxxx --appendonly yes
    networks:
      - api-network
      
networks:
  api-network:
    driver: bridge



    
