# FROM oraclelinux:8

# RUN  dnf -y install oracle-instantclient-release-el8 && \
#      dnf -y install oracle-instantclient-basic oracle-instantclient-devel oracle-instantclient-sqlplus && \
#      rm -rf /var/cache/dnf

# # Uncomment if the tools package is added
# # ENV PATH=$PATH:/usr/lib/oracle/21/client64/bin

# CMD ["sqlplus", "-v"]

FROM oraclelinux:7-slim

RUN  yum -y install oracle-instantclient-release-el7 && \
     yum -y install oracle-instantclient-basic oracle-instantclient-devel oracle-instantclient-sqlplus && \
     rm -rf /var/cache/yum

# Uncomment if the tools package is added
# ENV PATH=$PATH:/usr/lib/oracle/21/client64/bin

CMD ["sqlplus", "-v"]